### ISSUE TITLE
Create a table schema for table w/results of scans

### ISSUE THREAD

**Issue by alexclear** [IPMITMO/statan-research#38]
Create a ER-diagram or any other kind of formal or semi-formal description of how we are going to store scan results

**Comment by artemsnezhny** [comment]
Draft
![dbscheme](https://cloud.githubusercontent.com/assets/11491964/19493738/9c97d17a-9584-11e6-9633-b3c597d88126.png)

**Comment by alexclear** [comment]
I think we can safely join Results and AnalyzeResults because AnalyzeResults is just a linking table

**Comment by alexclear** [comment]
We should not forget to store language tag, say "Python", "Java", etc.

**Comment by artemsnezhny** [comment]
#46
