### ISSUE TITLE
Store scan results to files

### ISSUE THREAD

**Issue by alexclear** [IPMITMO/statan-research#41]
Store results of scans of "good" and "bad" repo to text files

**Comment by artemsnezhny** [comment]
Results for Coala rep: [Coala](https://github.com/IPMITMO/statan/tree/master/analyze/usingCoala/Coala)
Results for Ansible rep: [Ansible](https://github.com/IPMITMO/statan/tree/master/analyze/usingCoala/Ansible)

Interesting that even the Coala repository is not good.
