### ISSUE TITLE
Enhance the ER-diagram

### ISSUE THREAD

**Issue by alexclear** [IPMITMO/statan-research#46]
Add Projects, Repositories and SourceFiles.

**Comment by artemsnezhny** [comment]
@alexclear Why "Projects"? It simply contain issues.

**Comment by artemsnezhny** [comment]
![dbscheme](https://cloud.githubusercontent.com/assets/11491964/20032972/a7ad1b1c-a3a6-11e6-8d90-9844cbb764f2.png)
