### ISSUE TITLE
Scan Coala and Ansible repos w/RedBaron, attach results as files

### ISSUE THREAD

**Issue by alexclear** [IPMITMO/statan-research#48]

**Comment by artemsnezhny** [comment]
RedBaron is not an analyzer. "That include writing custom refactoring, generic refactoring, tools, IDE or directly modifying you source code into IPython with an higher and more powerful abstraction than the advanced texts modification tools that you find in advanced text editors and IDE."

**Comment by alexclear** [comment]
Since RedBaron is not a scanner, we postpone this task
