### ISSUE TITLE
Create an Excel chart comparing different static analyzers

### ISSUE THREAD

**Issue by alexclear** [IPMITMO/statan-research#58]

**Comment by alexclear** [comment]
We are mining Github - why not to use Github to compare analyzers?

**Comment by alexclear** [comment]
Examples:
https://docs.google.com/spreadsheets/d/1FY9d1di0wvb0E6y61skjrDt-FyLTyq792vR2E5YUhTk/edit

**Comment by alexclear** [comment]
https://docs.google.com/spreadsheets/d/1It0Vl_x97jLUUCmltbU5SVDaSCtnmDC8E9rVyAYGE3g/edit

**Comment by alexclear** [comment]
https://docs.google.com/spreadsheets/d/18UJKoS-3s8lUQ3Jhu90u95eoFsZyA3kgnoGSzrmqV2E/edit

**Comment by artemsnezhny** [comment]
[Python static analayzers](https://docs.google.com/spreadsheets/d/1AMbfHMVIW1YAoiHRSlFtV7imfGP2B5y3rFr_3k3i4RI/edit?usp=sharing)
