### ISSUE TITLE
Analyze Coala source code using Pylama

### ISSUE THREAD

**Issue by alexclear** [IPMITMO/statan-research#67]

**Comment by artemsnezhny** [comment]
Test results using command
`pylama -i C0111 -l "pylint,pyflakes" ../../sources/coala-0.9.0 > coala-0.9.0_pylint_pyflakes.txt`

Worth noting that the vast majority of detected errors are ignored in Coala own tests, for example, the whole directory "tests".
C0111: Missing %s docstring
[coala-0.9.0_pylint_pyflakes.txt](https://github.com/IPMITMO/statan/files/733423/coala-0.9.0_pylint_pyflakes.txt)

**Comment by artemsnezhny** [comment]
[coala-0.9.0_pylint_pyflakes (ignore).txt](https://github.com/IPMITMO/statan/files/736914/coala-0.9.0_pylint_pyflakes.ignore.txt)
