### ISSUE TITLE
Write and submit a paper on outcomes (a paper #1)

### ISSUE THREAD

**Issue by iradche** [IPMITMO/statan-research#7]
- [x] Create a plan of paper
- [x] Gather materials 
- [x] Collect links

**Comment by iradche** [comment]
https://docs.google.com/document/d/1Mdhcrv5WFDfrcNpRhUFqLDCO2BP2xqew5bzWdT9iguc/edit#

**Comment by artemsnezhny** [comment]
A start. Mining of materials.

**Comment by artemsnezhny** [comment]
https://docs.google.com/document/d/1cUIUvhshg9z7rRa7NicihtYHUHM1EnJtM325D_hjub0/edit?usp=sharing

**Comment by artemsnezhny** [comment]
https://1drv.ms/i/s!Alx6Xyvw4sk1gvRvnxiaIt5fhLgQ_A
@iradche, my photo
