### ISSUE TITLE
Create call sequence diagrams for Coala and Pylama

### ISSUE THREAD

**Issue by artemsnezhny** [IPMITMO/statan-research#73]

**Comment by artemsnezhny** [comment]
Diagram for Pylama
![pylama_short_sequence_diagram](https://cloud.githubusercontent.com/assets/11491964/22405976/58bc6f9c-e65b-11e6-9fa8-00f849861165.png)

**Comment by artemsnezhny** [comment]
Diagram for Coala
![coala_short_sequence_diagram](https://cloud.githubusercontent.com/assets/11491964/22406197/97d326c2-e65f-11e6-84e9-0a31f7dea374.png)

Also it's maybe helpful for this issue [coala#3647](https://github.com/coala/coala/issues/3647)

**Comment by alexclear** [comment]
We should probably add them to the PSI2017 paper

**Comment by alexclear** [comment]
#80
